#===============================================================================
# SEEKING
#===============================================================================
, frame-back-step
. frame-step 1 seek

LEFT seek -5 relative+exact
RIGHT seek 5 relative+exact

Ctrl+LEFT add chapter -1
Ctrl+RIGHT add chapter 1

0 seek 0 absolute-percent+exact
1 seek 10 absolute-percent+exact
2 seek 20 absolute-percent+exact
3 seek 30 absolute-percent+exact
4 seek 40 absolute-percent+exact
5 seek 50 absolute-percent+exact
6 seek 60 absolute-percent+exact
7 seek 70 absolute-percent+exact
8 seek 80 absolute-percent+exact
9 seek 90 absolute-percent+exact

#===============================================================================
# VOLUME
#===============================================================================
DOWN add volume -1
UP add volume 1

Shift+DOWN add volume -5
Shift+UP add volume 5

m cycle mute

#===============================================================================
# SUBTITLES
#===============================================================================
- add sub-font-size -1
+ add sub-font-size 1

k add sub-pos -1
j add sub-pos 1

c cycle sub-visibility

/ script-binding search-subs/list_subtitles

#===============================================================================
# SPEED
#===============================================================================
< add speed -0.1
> add speed 0.1

#===============================================================================
# PLAYLISTS
#===============================================================================
Ctrl+p playlist-prev
Ctrl+n playlist-next

#===============================================================================
# VIEW
#===============================================================================

Ctrl+MBTN_LEFT script-binding positioning/drag-to-pan
Ctrl+WHEEL_DOWN add video-zoom -0.1
Ctrl+WHEEL_UP add video-zoom 0.1

Ctrl+- add video-zoom -0.1
Ctrl++ add video-zoom 0.1

Ctrl+= no-osd set video-zoom 0; no-osd set panscan 0; no-osd set video-pan-x 0; no-osd set video-pan-y 0; no-osd set video-align-x 0; no-osd set video-align-y 0

#===============================================================================
# MISC
#===============================================================================
MBTN_LEFT cycle pause
SPACE cycle pause

f cycle fullscreen

q quit
Q quit-watch-later

: script-binding commands/open
? script-binding uosc/keybinds

C script-binding crop/toggle-crop
v script-binding clip/clip-set-timestamp
