input-default-bindings=no
keep-open=yes
keep-open-pause=yes

sub-file-paths=subs:Subs:subtitles:Subtitles
sub-auto=all

osd-font-size=12

#===============================================================================
# AUTO PROFILES
#===============================================================================
[gif]
profile-cond=path:find("%.gif$")
loop-file=inf
