# Location of plugin configs for rocks-config.nvim
#   - the file name for a respective plugin is searched for using a set of heuristics
#     - https://github.com/nvim-neorocks/rocks-config.nvim?tab=readme-ov-file#plugins_dir
[config]
plugins_dir = "config/plugins/configurations/"
auto_setup = false

# Location of lazy specs written in lua for rocks-lazy.nvim
#   - all files in this directory will be imported (name does not matter)
#   - for plugins in this dir, opt must be set to true in their rockspec in order for them to be lazy loaded
[rocks_lazy]
import = "config/plugins/lazy_specs_post"

# List of non-Neovim rocks, e.g. `toml`
[rocks]

# List of Neovim plugins to install
#   - plugins with a dot in the name must be quoted
[plugins]

# ====== LOCAL PLUGINS ======
"bartender.nvim" = { dir = "~/projects/bartender.nvim", opt = false }
"palette.nvim" = { dir = "~/projects/palette.nvim", opt = false }
"dye.nvim" = { dir = "~/projects/dye.nvim", opt = false }
# "smoothie.nvim" = { dir = "~/projects/smoothie.nvim", config = "plugin.mysmoothie" }

# ====== LUAROCK PLUGINS ======
"actions-preview.nvim" = { version = "scm", opt = true }
"aerial.nvim" = { version = "scm", opt = true }
"conform.nvim" = { version = "8.4.0", opt = true }
"diffview.nvim" = { version = "scm", opt = true }
"flatten.nvim" = { version = "0.5.1", opt = false }
"oil.nvim" = { version = "2.14.0", opt = true }
"persistence.nvim" = { version = "scm", opt = true }
"rainbow-delimiters.nvim" = { version = "0.8.0", opt = true }
"rocks-config.nvim" = { version = "3.1.0", opt = false }
"rocks-dev.nvim" = { version = "1.7.0", opt = false }
"rocks-git.nvim" = { version = "2.5.2", opt = false }
"rocks-lazy.nvim" = { version = "1.1.1" }
"rocks.nvim" = { version = "2.40.0", opt = false }
"telescope.nvim" = { version = "scm", opt = true }
# fzf-lua = { version = "0.0.1719", opt = true }
luasnip = { version = "2.3.0", opt = true }
neogen = { version = "2.20.0", opt = false }
neogit = { version = "2.0.0", opt = true }
neorg = { version = "9.1.1", opt = true }
nvim-dap = { version = "0.9.0", opt = true }
nvim-dap-ui = { version = "4.0.0", opt = true }
nvim-dap-virtual-text = { version = "scm", opt = true }
nvim-lint = { version = "scm", opt = true }
nvim-lspconfig = { version = "1.4.0", opt = true }
nvim-navic = { version = "scm", opt = true }
nvim-notify = { version = "3.15.0", opt = true }
nvim-surround = { version = "2.1.5", opt = true }
nvim-treesitter-context = { version = "scm", opt = true }
nvim-treesitter-textobjects = { version = "scm", opt = true }
nvim-ts-autotag = { version = "scm", opt = true }

# ====== GIT PLUGINS ======
[plugins."fzf-lua"]
git = "phanen/fzf-lua"
rev = "fix-fifo-block"
opt = true

[plugins."blame.nvim"]
git = "FabijanZulj/blame.nvim"
rev = "39bb4cda9e658d053a43919b10ca52c0a4d738e1"
opt = true

[plugins."satellite.nvim"]
git = "lewis6991/satellite.nvim"
rev = "main"
opt = true

[plugins."lasso.nvim" ]
git = "austinliuigi/lasso.nvim"
rev = "321bb52116f470c43d83f78fa8549cefdb7f3cec"
opt = true

[plugins."blink.cmp"]
git = "Saghen/blink.cmp"
rev = "v0.11.0"
opt = true
config = "config.plugins.configurations.blink"

[plugins."telescope-fzf-native.nvim" ]
git = "nvim-telescope/telescope-fzf-native.nvim"
rev = "dae2eac9d91464448b584c7949a31df8faefec56"
opt = true
build = "make"

[plugins.cmp-buffer ]
git = "hrsh7th/cmp-buffer"
rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa"
opt = true

[plugins.cmp-calc ]
git = "hrsh7th/cmp-calc"
rev = "5947b412da67306c5b68698a02a846760059be2e"
opt = true

[plugins.cmp-cmdline ]
git = "hrsh7th/cmp-cmdline"
rev = "d250c63aa13ead745e3a40f61fdd3470efde3923"
opt = true

[plugins.cmp-cmdline-history ]
git = "dmitmel/cmp-cmdline-history"
rev = "003573b72d4635ce636234a826fa8c4ba2895ffe"
opt = true

[plugins.cmp-dap ]
git = "rcarriga/cmp-dap"
rev = "ea92773e84c0ad3288c3bc5e452ac91559669087"
opt = true

[plugins.cmp-digraphs ]
git = "dmitmel/cmp-digraphs"
rev = "5efc1f0078d7c5f3ea1c8e3aad04da3fd6e081a9"
opt = true

[plugins.cmp-luasnip ]
git = "saadparwaiz1/cmp_luasnip"
rev = "98d9cb5c2c38532bd9bdb481067b20fea8f32e90"
opt = true

[plugins.cmp-nvim-lsp ]
git = "hrsh7th/cmp-nvim-lsp"
rev = "99290b3ec1322070bcfb9e846450a46f6efa50f0"
opt = true

[plugins.cmp-nvim-lsp-signature-help ]
git = "hrsh7th/cmp-nvim-lsp-signature-help"
rev = "031e6ba70b0ad5eee49fd2120ff7a2e325b17fa7"
opt = true

[plugins.cmp-nvim-lua ]
git = "hrsh7th/cmp-nvim-lua"
rev = "f12408bdb54c39c23e67cab726264c10db33ada8"
opt = true

[plugins.cmp-path ]
git = "hrsh7th/cmp-path"
rev = "91ff86cd9c29299a64f968ebb45846c485725f23"
opt = true

[plugins.firenvim ]
git = "glacambre/firenvim"
rev = "c6e37476ab3b58cf01ababfe80ec9335798e70e5"
build = ":call firenvim#install(0)"

[plugins.nvim-cmp ]
git = "hrsh7th/nvim-cmp"
rev = "v0.0.2"
opt = true

[plugins.nvim-colorizer ]
git = "mehalter/nvim-colorizer.lua"
rev = "72aba5511b6af8405f26c3922c12a17bf8a680d1"
opt = true

[plugins.nvim-silicon ]
git = "michaelrommel/nvim-silicon"
rev = "v1.0.0"
opt = true

[plugins.nvim-treesitter ]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.3^{}" # use main branch when neorg doesn't require nvim-treesitter as a dependency
# branch = "main"
opt = true

[plugins.vim-easy-align ]
git = "junegunn/vim-easy-align"
rev = "2.9.7^{}"
opt = true

[plugins.vim-matchup ]
git = "andymass/vim-matchup"
rev = "v0.7.3"
opt = true

[plugins.vim-mundo ]
git = "simnalamburt/vim-mundo"
rev = "v3.0.1"
opt = true

[plugins.vim-smoothie ]
git = "psliwka/vim-smoothie"
rev = "df1e324e9f3395c630c1c523d0555a01d2eb1b7e"
opt = true

[plugins.vim-startuptime ]
git = "dstein64/vim-startuptime"
rev = "v4.5.0"
opt = true

[plugins.wordmotion ]
git = "chaoren/vim-wordmotion"
rev = "81d9bd298376ab0dc465c85d55afa4cb8d5f47a1"
opt = true

[plugins.committia ]
git = "rhysd/committia.vim"
rev = "c8c0f255e8090ed90dd9d5dd2e8672994f8e3671"
opt = false
