# Location of plugin configs for rocks-config.nvim
[config]
plugins_dir = "config/plugins/configurations/"
auto_setup = false

# Location of lazy specs written in lua for rocks-lazy.nvim
#   - all files in this directory will be imported (name does not matter)
#   - for plugins in this dir, opt must be set to true in their rockspec in order for them to be lazy loaded
[rocks_lazy]
import = "config/plugins/lazy_specs_post"

# List of non-Neovim rocks, e.g. `toml`
[rocks]

# List of Neovim plugins to install
#   - plugins with a dot in the name must be quoted
[plugins]

# ====== LUAROCKS ======
"actions-preview.nvim" = { version = "scm", opt = true }
"aerial.nvim" = { version = "scm", opt = true }
"conform.nvim" = { version = "6.0.0", opt = true }
"diffview.nvim" = { version = "scm", opt = true }
"flatten.nvim" = { version = "0.5.1", opt = true }
"oil.nvim" = { version = "2.11.0", opt = true }
"rainbow-delimiters.nvim" = { version = "0.4.0", opt = true }
"rocks-config.nvim" = { version = "2.1.3" }
"rocks-dev.nvim" = { version = "1.2.3", opt = true }
"rocks-git.nvim" = { version = "1.5.1", opt = true }
"rocks-lazy.nvim" = { version = "1.0.0" }
"rocks.nvim" = { version = "2.35.1" }
"telescope.nvim" = { version = "scm", opt = true }
luasnip = { version = "2.3.0", opt = true }
neogen = { version = "2.17.1", opt = false }
neogit = { version = "1.0.0", opt = true }
neorg = { version = "8.9.0", opt = true }
nvim-dap = { version = "0.8.0", opt = true }
nvim-dap-ui = { version = "4.0.0", opt = true }
nvim-dap-virtual-text = { version = "scm", opt = true }
nvim-lint = { version = "scm", opt = true }
nvim-lspconfig = { version = "0.1.8", opt = true }
nvim-navic = { version = "scm", opt = true }
nvim-notify = { version = "3.13.5", opt = true }
nvim-surround = { version = "2.1.5", opt = true }
nvim-treesitter-textobjects = { version = "scm", opt = true }
nvim-ts-autotag = { version = "scm", opt = true }

# ====== GIT PLUGINS ======
"blame.nvim" = { git = "FabijanZulj/blame.nvim", opt = true }
"lasso.nvim" = { git = "austinliuigi/lasso.nvim", opt = true }
"telescope-fzf-native.nvim" = { git = "nvim-telescope/telescope-fzf-native.nvim", build = "make", opt = true }
cmp-buffer = { git = "hrsh7th/cmp-buffer", opt = true }
cmp-calc = { git = "hrsh7th/cmp-calc", opt = true }
cmp-cmdline = { git = "hrsh7th/cmp-cmdline", opt = true }
cmp-cmdline-history = { git = "dmitmel/cmp-cmdline-history", opt = true }
cmp-dap = { git = "rcarriga/cmp-dap", opt = true }
cmp-digraphs = { git = "dmitmel/cmp-digraphs", opt = true }
cmp-luasnip = { git = "saadparwaiz1/cmp_luasnip", opt = true }
cmp-nvim-lsp = { git = "hrsh7th/cmp-nvim-lsp", opt = true }
cmp-nvim-lsp-signature-help = { git = "hrsh7th/cmp-nvim-lsp-signature-help", opt = true }
cmp-nvim-lua = { git = "hrsh7th/cmp-nvim-lua", opt = true }
cmp-path = { git = "hrsh7th/cmp-path", opt = true }
firenvim = { git = "glacambre/firenvim", build = ":call firenvim#install(0)" }
nvim-cmp = { git = "hrsh7th/nvim-cmp", opt = true }
nvim-colorizer = { git = "mehalter/nvim-colorizer.lua", opt = true }
nvim-silicon = { git = "michaelrommel/nvim-silicon", opt = true }
nvim-treesitter = { git = "nvim-treesitter/nvim-treesitter", opt = true }
vim-easy-align = { git = "junegunn/vim-easy-align", opt = true }
vim-matchup = { git = "andymass/vim-matchup", opt = true }
vim-mundo = { git = "simnalamburt/vim-mundo", opt = true }
vim-smoothie = { git = "psliwka/vim-smoothie", opt = true }
vim-startuptime = { git = "dstein64/vim-startuptime", opt = true }
wordmotion = { git = "chaoren/vim-wordmotion", opt = true }

# ====== LOCAL PLUGINS ======
"bartender.nvim" = { dir = "~/projects/bartender.nvim", opt = false }
"palette.nvim" = { dir = "~/projects/palette.nvim", opt = false }
# "smoothie.nvim" = { dir = "~/projects/smoothie.nvim", config = "plugin.mysmoothie" }
