# Location of plugin configs for rocks-config.nvim
#   - the file name for a respective plugin is searched for using a set of heuristics
#     - https://github.com/nvim-neorocks/rocks-config.nvim?tab=readme-ov-file#plugins_dir
[config]
plugins_dir = "config/plugins/configurations/"
auto_setup = false

# Location of lazy specs written in lua for rocks-lazy.nvim
#   - all files in this directory will be imported (name does not matter)
#   - for plugins in this dir, opt must be set to true in their rockspec in order for them to be lazy loaded
[rocks_lazy]
import = "config/plugins/lazy_specs_post"

# List of non-Neovim rocks, e.g. `toml`
[rocks]

# List of Neovim plugins to install
#   - plugins with a dot in the name must be quoted
[plugins]

#===========================================================================================
# LOCAL PLUGINS
#===========================================================================================
# "bartender.nvim" = { dir = "~/projects/bartender.nvim", opt = true }
"bartender.nvim" = { git = "austinliuigi/bartender.nvim", rev = "main", opt = true }

# "palette.nvim" = { dir = "~/projects/palette.nvim", opt = false }
"palette.nvim" = { git = "austinliuigi/palette.nvim", rev = "main", opt = false }

# "dye.nvim" = { dir = "~/projects/dye.nvim", opt = false }
"dye.nvim" = { git = "austinliuigi/dye.nvim", rev = "main", opt = false }

# "portal.nvim" = { dir = "~/projects/portal.nvim", opt = true }
"portal.nvim" = { git = "austinliuigi/portal.nvim", rev = "main", opt = true }

# ----- FORKS -----
neorg = { dir = "~/projects/_forks/neorg", opt = true }
"lua-utils.nvim" = { version = "1.0.2", opt = false }
"pathlib.nvim" = { version = "2.2.3", opt = false }

# neogit = { dir = "~/projects/_forks/neogit", opt = true }
# "smoothie.nvim" = { dir = "~/projects/smoothie.nvim", config = "plugin.mysmoothie" }


#===========================================================================================
# LUAROCK PLUGINS
#===========================================================================================
# "actions-preview.nvim" = { version = "scm-8", opt = true }
# "aerial.nvim" = { version = "scm", opt = true }
"conform.nvim" = { version = "9.1.0", opt = true }
"diffview.nvim" = { version = "scm", opt = true }
"flatten.nvim" = { version = "0.5.1", opt = false }
"indent-blankline.nvim" = { version = "scm", opt = true }
"oil.nvim" = { version = "2.14.0", opt = true }
"rainbow-delimiters.nvim" = { version = "0.8.0", opt = true }
"rocks-config.nvim" = { version = "3.1.0", opt = false }
"rocks-dev.nvim" = { version = "1.8.1", opt = false }
"rocks-git.nvim" = { version = "2.5.5", opt = false }
"rocks-lazy.nvim" = { version = "1.2.0", opt = false }
"rocks.nvim" = { version = "2.49.0", opt = false }
"snacks.nvim" = { version = "scm", opt = true }
# "todo-comments.nvim" = { version = "scm", opt = true }
"venn.nvim" = { version = "scm", opt = true }
fzf-lua = { version = "0.0.2693", opt = true } # 2063 works, 2068 doesn't work
luasnip = { version = "2.3.0", opt = true }
neogen = { version = "2.20.0", opt = true }
# neogit = { version = "scm", opt = true }
# neorg = { version = "9.3.0", opt = false }
# neorg-interim-ls = { version = "2.1.1", opt = false }
nvim-dap = { version = "0.9.0", opt = true }
nvim-dap-ui = { version = "4.0.0", opt = true }
nvim-dap-virtual-text = { version = "scm", opt = true }
nvim-lint = { version = "scm", opt = true }
nvim-lspconfig = { version = "2.5.0", opt = false }
# nvim-navic = { version = "scm", opt = true }
nvim-notify = { version = "3.15.0", opt = false }
nvim-surround = { version = "4.0.5", opt = true }
nvim-treesitter-context = { version = "scm", opt = true }
nvim-treesitter-textobjects = { version = "scm", opt = true }
nvim-ts-autotag = { version = "scm", opt = true }

#===========================================================================================
# GIT PLUGINS
#===========================================================================================
"actions-preview.nvim" = { git = "aznhe21/actions-preview.nvim", rev = "0ac9c2aa3cfc8c885321c0862b50b6b1c3392405", opt = true }
"aerial.nvim" = { git = "stevearc/aerial.nvim", rev = "master", opt = true }
"blame.nvim" = { git = "FabijanZulj/blame.nvim", rev = "39bb4cda9e658d053a43919b10ca52c0a4d738e1", opt = true }
"satellite.nvim" = { git = "lewis6991/satellite.nvim", rev = "main", opt = true }
"lasso.nvim"  = { git = "austinliuigi/lasso.nvim", rev = "321bb52116f470c43d83f78fa8549cefdb7f3cec", opt = true }
"codecompanion.nvim" = { git = "olimorris/codecompanion.nvim", rev = "v19.22.0", opt = true }
"blink.cmp" = { git = "Saghen/blink.cmp", rev = "v1.10.2", opt = true, config = "config.plugins.configurations.blink" }
blink-cmp-git = { git = "Kaiser-Yang/blink-cmp-git", rev = "master", opt = false }
# cmp-dap  = { git = "rcarriga/cmp-dap", rev = "ea92773e84c0ad3288c3bc5e452ac91559669087", opt = true }
firenvim  = { git = "glacambre/firenvim", rev = "c6e37476ab3b58cf01ababfe80ec9335798e70e5", build = ":call firenvim#install(0)" }
nvim-colorizer  = { git = "mehalter/nvim-colorizer.lua", rev = "72aba5511b6af8405f26c3922c12a17bf8a680d1", opt = true }
nvim-silicon  = { git = "michaelrommel/nvim-silicon", rev = "v1.0.0", opt = true }
"resession.nvim" = { git = "stevearc/resession.nvim", rev = "master", opt = true }
"quicker.nvim" = { git = "stevearc/quicker.nvim", rev = "master", opt = true }
wrapwidth = { git = "rickhowe/wrapwidth", rev = "a766191a1cd24ebb95d669ebd4a440c50d7f4422", opt = true }
vim-easy-align  = { git = "junegunn/vim-easy-align", rev = "2.9.7^{}", opt = true }
vim-matchup  = { git = "andymass/vim-matchup", rev = "master", opt = true }
vim-mundo  = { git = "simnalamburt/vim-mundo", rev = "master", opt = true }
vim-smoothie  = { git = "psliwka/vim-smoothie", rev = "df1e324e9f3395c630c1c523d0555a01d2eb1b7e", opt = true }
vim-startuptime  = { git = "dstein64/vim-startuptime", rev = "v4.5.0", opt = true }
wordmotion  = { git = "chaoren/vim-wordmotion", rev = "81d9bd298376ab0dc465c85d55afa4cb8d5f47a1", opt = true }
committia  = { git = "rhysd/committia.vim", rev = "c8c0f255e8090ed90dd9d5dd2e8672994f8e3671", opt = false }
nvim-treesitter  = { git = "nvim-treesitter/nvim-treesitter", rev = "main", opt = false }
"todo-comments.nvim" = { git = "folke/todo-comments.nvim", rev = "main", opt = true }
neogit = { git = "NeogitOrg/neogit", rev = "master", opt = true }
nvim-navic = { git = "SmiteshP/nvim-navic", rev = "f5eba192f39b453675d115351808bd51276d9de5", opt = true }
# neorg = { git = "nvim-neorg/neorg", rev = "main", opt = false }

# HACK: this plenary takes priority over the luarocks simply because it gets searched first; remove this when plenary creates a new luarocks release (https://github.com/nvim-lua/plenary.nvim/issues/629)
"plenary.nvim" = { git = "nvim-lua/plenary.nvim", rev = "master", opt = false }


# "telescope.nvim" = { version = "scm", opt = true }
# "telescope-fzf-native.nvim"  = { git = "nvim-telescope/telescope-fzf-native.nvim", rev = "dae2eac9d91464448b584c7949a31df8faefec56", opt = true, build = "make" }
