source = ~/.local/share/hyprland/palette.conf
source = ~/.local/share/hyprland/font.conf
$font = Jetbrains Mono Nerd Font

# GENERAL
general {
  hide_cursor = false
  ignore_empty_input = false
  immediate_render = false
}

# enable fingerprint authentication
auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
  monitor =
  path = ~/.cache/txn/wallpaper.png   # supports png, jpg, webp (no animations, though)
  color = rgb($base01)
  blur_passes = 2 # 0 disables blurring
}

input-field {
  monitor =
  size = 175, 35
  outline_thickness = 2
  dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
  dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
  dots_center = true
  dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
  outer_color = rgba($base01ff)
  inner_color = rgba($base04aa)
  font_color = rgb($base02)
  font_family = $font
  placeholder_text = <i><span foreground="##$base02">Password...</span></i>
  fade_on_empty = false
  fade_timeout = 1000 # Milliseconds before fade_on_empty is triggered.
  hide_input = false
  rounding = -1 # -1 means complete rounding (circle/oval)
  check_color = rgb($base09)
  fail_color = rgb($base08) # if authentication failed, changes outer_color and fail message color
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
  capslock_color = rgb($base0A)
  numlock_color = -1
  bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
  invert_numlock = false # change color if numlock is off
  swap_font_color = false # see docs

  position = 0, -100
  halign = center
  valign = center
}

# TIME
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%-I:%M%p")"
  color = rgb($base01)
  #color = rgba(255, 255, 255, 0.6)
  font_size = 120
  font_family = $font
  position = 0, -300
  halign = center
  valign = top
}

# USER
label {
  monitor =
  text = Hi there, $USER
  color = rgb($base01)
  font_size = 18
  font_family = $font
  position = 0, -30
  halign = center
  valign = center
}

# FORTUNE
# label {
#   monitor =
#   text = cmd[update:0] echo "$(fortune)" 
#   color = rgb($base0F)
#   font_size = 14
#   font_family = $font
#   position = 0, 30
#   halign = center
#   valign = bottom
# }
