#!/usr/bin/env bash

control="$1"

function notify() {
    brightness="$(printf "%0.0f\n" "$(echo "scale=5; $(brightnessctl get)/$(brightnessctl max) * 100" | bc)")"

    if [ $brightness -ge 75 ]; then
        icon="$HOME/.cache/txn/icons/brightness-high.png"
    elif [ $brightness -ge 35 ]; then
        icon="$HOME/.cache/txn/icons/brightness-medium.png"
    else
        icon="$HOME/.cache/txn/icons/brightness-low.png"
    fi

    echo "Brightness is $brightness"

    notify-send --replace-id=1998 --urgency=low --icon="$icon" --hint=int:value:"$brightness" "Brightness" "$brightness"
}

brightness="$(printf "%0.0f\n" "$(echo "scale=5; $(brightnessctl get)/$(brightnessctl max) * 100" | bc)")"
case "$control" in
    increase)
        brightnessctl set $((brightness + 5))% >/dev/null
        # brightnessctl set 5%+ >/dev/null
        ;;

    decrease)
        brightnessctl set $((brightness - 5))% >/dev/null
        # brightnessctl set 5%- >/dev/null
        ;;

    *)
        echo "usage: $0 CONTROL" >&2
        exit 1
        ;;
esac

notify
