#!/usr/bin/env bash

# ========== INIT ==========

modes="\
image
video
audio/video\
"

if [ ! -z "$1" ]; then
  mode="$1"
else
  mode="$(echo -e "$modes" | fuzzel --dmenu)"
  if [ -z $mode ]; then
      exit 0
  fi
fi

case "$mode" in
  "image")
    cmd="grim -t png -g {{geometry}} {{filepath}}"
    ext="png"
    ;;
  "video")
    cmd="wl-screenrec -g {{geometry}} -f {{filepath}}"
    ext="mp4"
    ;;
  "audio/video")
    cmd="wl-screenrec --audio -g {{geometry}} -f {{filepath}}"
    ext="mp4"
    ;;
esac



# ========== FUNCTIONS ==========

function interpolate_cmd() {
  local geometry="$1"
  local filepath="$2"

  eval "$(echo "$cmd" | sed -e "s/{{geometry}}/\"$geometry\"/g" -e "s;{{filepath}};\"$filepath\";g")"
}

function exit_if_error() {
    if [ "$?" != 0 ]; then
        echo "$1" >&2
        notify-send --urgency=normal "Screenshot" "$1"
        exit
    fi
}

function notify() {
    if [ "$mode" == "image" ]; then
      echo "Screenshot saved to $1"
      notify-send --urgency=normal --icon="$HOME/.cache/txn/icons/image.png" "Screenshot" "Saved to $1"
    else
      echo "Video saved to $1"
      notify-send --urgency=normal --icon="$HOME/.cache/txn/icons/image.png" "Video" "Saved to $1"
    fi
}

function output_locations() {
    echo "clipboard"
    echo "${TMPDIR:-/tmp}"
    fd . ~ --type=d | sed 's:/$::'
}



# ========== MAIN ==========

dir="$(output_locations | fuzzel --dmenu --prompt="Save to: ")"
exit_if_error "Cancelled"

# ---------- SAVE TO CLIPBOARD ----------
if [ "$dir" == "clipboard" ]; then
  slurp="$(slurp -d)"
  exit_if_error "Cancelled"

  # ----- SCREENSHOT -----
  if [ "$mode" == "image" ]; then
    interpolate_cmd "${slurp}" - | wl-copy -t image/png

  # ----- SCREENREC -----
  else
    echo $cmd
    tmpfile="$(mktemp -t screenrec.XXXXXX.mp4)"
    interpolate_cmd "${slurp}" "$tmpfile"
    exit_if_error "Unable to record screen"
    cat "$tmpfile" | wl-copy -t video/mp4
  fi

  notify "$dir"

# ---------- SAVE TO FILE ----------
else
  default_filename="$(date +"%FT%H-%M-%S").${ext}"
  filename="$(fuzzel --dmenu --placeholder="$default_filename" --prompt="Filename: ${dir}/")"
  exit_if_error "Cancelled"

  if [ ! -n "${filename}" ]; then
      filename="${default_filename}"
  fi
  filepath="${dir}/${filename}"

  if [ -e "${filepath}" ]; then
    if [ ! "$(fuzzel --dmenu --prompt="Overwrite existing file ${filepath}? (y/[n]): ")" == "y" ]; then
      false
      exit_if_error "Cancelled"
    fi
  fi

  slurp="$(slurp -d)"
  exit_if_error "Cancelled"

  interpolate_cmd "${slurp}" "${filepath}"
  exit_if_error "Unable to capture screen"

  notify "$filepath"
fi
