#!/usr/bin/env bash

# ========== GTD ==========
if [ ! -d ~/todo ]; then
    echo "ERROR: directory ~/todo does not exist"
    exit 1
fi

cd ~/todo


# ========== NVIM ==========
server_addr="${TMPDIR:-/tmp}/todo.nvim.pipe"

if [ ! -e "${server_addr}" ]; then
    # create new instance
    nvim --listen "${server_addr}" -c "Todo"
else
    # connect to existing instance
    nvim --server "${server_addr}" --remote-ui
fi
