# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#FFFFFF", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#@base00@"

# Main text color
theme[main_fg]="#@base05@"

# Title color for boxes
theme[title]="#@base06@"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#@base09@"

# Background color of selected items
theme[selected_bg]="#@base01@"

# Foreground color of selected items
theme[selected_fg]="#@base0A@"

# Color of inactive/disabled text
theme[inactive_fg]="#@base03@"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#@base03@"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#@base0B@"

# Cpu box outline color
theme[cpu_box]="#@base02@"

# Memory/disks box outline color
theme[mem_box]="#@base02@"

# Net up/down box outline color
theme[net_box]="#@base02@"

# Processes box outline color
theme[proc_box]="#@base02@"

# Box divider line and small boxes line color
theme[div_line]="#@base02@"

# Temperature graph colors
theme[temp_start]="#@base0C@"
theme[temp_mid]="#@base0A@"
theme[temp_end]="#@base08@"

# CPU graph colors
theme[cpu_start]="#@base0B@"
theme[cpu_mid]="#@base0A@"
theme[cpu_end]="#@base08@"

# Mem/Disk free meter
theme[free_start]="#@base0B@"
theme[free_mid]=""
theme[free_end]=""

# Mem/Disk cached meter
theme[cached_start]="#@base0D@"
theme[cached_mid]=""
theme[cached_end]=""

# Mem/Disk available meter
theme[available_start]="#@base09@"
theme[available_mid]=""
theme[available_end]="#@base0A@"

# Mem/Disk used meter
theme[used_start]="#@base0F@"
theme[used_mid]=""
theme[used_end]=""

# Download graph colors
theme[download_start]="#@base0E@" # low speeds
theme[download_mid]="#@base0E@" # medium speeds
theme[download_end]="#@base0E@" # high speeds

# Upload graph colors
theme[upload_start]="#@base0D@" # low speeds
theme[upload_mid]="#@base0D@" # medium speeds
theme[upload_end]="#@base0D@" # high speeds

# vim: set ft=conf :
