[General]
  Backend = "gist" # the backend service to sync snippets
  Cmd = [] # the command to execute the snippet with
  Color = false # enables output coloring with fzf, same as '--color' flag
  Column = 40 # column size for list command
  Editor = "nvim" # your favorite text editor
  Format = "$command    ($description)  [$tags]" # controls the format of the output when searching
  SelectCmd = "fzf --ansi --layout=reverse --border --height=90% --pointer=* --cycle --prompt=Snippets:" # selector command for edit command (fzf or peco)
  SnippetFile = "~/.config/pet/snippet.toml" # specify snippet directory
  SortBy = "recency" # specify how snippets get sorted (recency (default), -recency, description, -description, command, -command, output, -output)

[Gist]
  Public = false
  access_token = ""
  auto_sync = false
  file_name = "pet-snippet.toml"
  gist_id = ""

[GitLab]
  ID = ""
  Url = ""
  Visibility = "private"
  access_token = ""
  auto_sync = false
  file_name = "pet-snippet.toml"
  skip_ssl = false

[GHEGist]
  Public = false
  access_token = ""
  auto_sync = false
  base_url = ""
  file_name = ""
  gist_id = ""
  upload_url = ""
