require("nvim-navic").setup({
  icons = {
    Array = "󰅪 ",
    Boolean = "◩ ",
    Class = "󰠱 ",
    Constant = " ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = "󰈙 ",
    Function = "󰊕 ",
    Interface = "󰕘 ",
    Key = " ",
    Keyword = "",
    Method = "󰊕 ",
    Module = " ",
    Namespace = " ",
    Null = " ",
    Number = "󰎠 ",
    Object = "󱢩 ",
    Operator = "󰆕 ",
    Package = " ",
    Property = " ",
    String = " ",
    Struct = " ",
    TypeParameter = "󰓼 ",
    Variable = "󰀫 ",
  },
  lsp = {
    auto_attach = true,
  },
  highlight = true,
  click = true,
  separator = " > ",
  depth_limit = 0,
  depth_limit_indicator = "..",
})
