log-file: /dev/null
input-file: ""
output-file: ""
ignore-dirs:
    - /proc
    - /dev
    - /sys
    - /run
ignore-dir-patterns: []
ignore-from-file: ""
max-cores: 4
sequential-scanning: false
show-apparent-size: false
show-relative-size: false
show-annexed-size: false
show-item-count: false
show-mtime: false
no-color: false
no-mouse: false
non-interactive: false
no-progress: false
no-unicode: false
no-cross: false
no-hidden: false
no-delete: false
follow-symlinks: false
profiling: false
const-gc: false
use-storage: false
storage-path: /tmp/badger
read-from-storage: false
summarize: false
top: 0
use-si-prefix: false
no-prefix: false
change-cwd: false
delete-in-background: false
delete-in-parallel: false
sorting:
    by: ""
    order: ""
